import React, { createContext, useCallback, useContext, useEffect, useState } from "react";
import * as SecureStore from "expo-secure-store";
import { I18nManager, Platform } from "react-native";

export type Lang = "en" | "fr" | "ar";

export const LANGS: { code: Lang; label: string; native: string }[] = [
  { code: "en", label: "English", native: "English" },
  { code: "fr", label: "French", native: "Français" },
  { code: "ar", label: "Arabic", native: "العربية" },
];

const STORAGE_KEY = "sp_lang";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const dict: Record<Lang, Record<string, string>> = {
  en: {
    // Brand
    "app.name": "khedmaPro",
    // Onboarding
    "onboarding.title": "Trusted pros\nat your fingertips.",
    "onboarding.subtitle": "Browse vetted service providers instantly — no account needed to search or book.",
    "onboarding.browse": "Browse services",
    "onboarding.iamProvider": "I'm a service provider",
    // Landing
    "landing.pilotBadge": "MADE FOR ALGERIA",
    "landing.heroTitle": "Your city's trusted pros,\none tap away.",
    "landing.heroSubtitle": "Book plumbers, electricians, cleaners, tutors and more — vetted, rated, and ready across all 58 wilayas.",
    "landing.f1Title": "Verified pros",
    "landing.f1Sub": "ID-checked service providers you can trust.",
    "landing.f2Title": "Instant booking",
    "landing.f2Sub": "Book at the listed rate or request a custom quote.",
    "landing.f3Title": "In-app chat",
    "landing.f3Sub": "Message before you commit. Numbers stay private.",
    "landing.f4Title": "Real ratings",
    "landing.f4Sub": "From clients who actually booked. No fakes.",
    "landing.trustWilayas": "Wilayas",
    "landing.trustLangs": "Languages",
    "landing.trustTrial": "Days free trial",
    "onboarding.haveAccount": "Have a provider account?",
    "onboarding.signIn": "Sign in",
    // Home
    "home.helloGuest": "Find a pro",
    "home.hello": "Hello",
    "home.searchPlaceholder": "Search providers, services...",
    "home.categoryFilter": "Category",
    "home.scope.filterBy": "Distance",
    "filters.title": "Filters",
    "filters.distance": "Distance",
    "filters.category": "Category",
    "filters.verifiedOnly": "Verified providers only",
    "filters.verifiedOnlySub": "Only show providers with verified ID.",
    "filters.apply": "Apply filters",
    "filters.reset": "Reset",
    "home.promoBadge": "NEW",
    "home.promoTitle": "Book vetted pros\nacross Algeria",
    "home.promoSub": "Trusted service providers, transparent pricing.",
    "home.categories": "Categories",
    "home.all": "All",
    "home.topRated": "Top rated",
    "home.allProviders": "All providers",
    "home.noResults": "No providers found",
    "home.headerSignIn": "Sign in",
    "home.scope.km": "Within {km} km",
    "home.scope.wilaya": "By wilaya",
    "home.scope.country": "All Algeria",
    "home.distanceKm": "{km} km away",
    "home.distanceMeters": "{m} m away",
    "home.locationDenied": "Location off — showing your wilaya. Enable location to search by radius.",
    // Categories
    "cat.plumbing": "Plumbing",
    "cat.electrical": "Electrical",
    "cat.cleaning": "Cleaning",
    "cat.carpentry": "Carpentry",
    "cat.painting": "Painting",
    "cat.landscaping": "Landscaping",
    "cat.it_support": "IT Support",
    "cat.admin_consulting": "Administrative Consultants",
    "cat.education": "Education (Private Tutoring)",
    "cat.photography": "Photography",
    "cat.moving": "Moving",
    // Provider detail
    "provider.verified": "Verified",
    "provider.reviews": "Reviews",
    "provider.noReviews": "No reviews yet. Be the first!",
    "provider.perHour": "DZD / hour",
    "provider.perTask": "DZD / task",
    "provider.requestBooking": "Request Booking",
    "provider.writeReview": "Write a review",
    // Booking
    "booking.title": "Request booking",
    "booking.selectDate": "Select date",
    "booking.selectTime": "Select time",
    "booking.rateType": "Rate type",
    "booking.hourly": "Hourly",
    "booking.task": "Task",
    "booking.hours": "Estimated hours",
    "booking.description": "Task description",
    "booking.descriptionPh": "Describe what you need done...",
    "booking.address": "Address",
    "booking.addressPh": "Street, city",
    "booking.yourInfo": "Your contact info",
    "booking.name": "Full name",
    "booking.phone": "Phone",
    "booking.email": "Email (optional)",
    "booking.total": "Estimated total",
    "booking.confirm": "Confirm",
    "booking.success": "Booking requested!",
    "booking.successSub": "will respond shortly.",
    "booking.viewBookings": "View bookings",
    "booking.done": "Done",
    "booking.errFill": "Please add task description and address",
    "booking.errGuest": "Please enter your name and phone",
    // Bookings tab
    "bookings.title": "My bookings",
    "bookings.all": "All",
    "bookings.pending": "Pending",
    "bookings.confirmed": "Confirmed",
    "bookings.completed": "Completed",
    "bookings.empty": "No bookings yet",
    "bookings.accept": "Accept",
    "bookings.decline": "Decline",
    "bookings.markComplete": "Mark complete",
    "bookings.cancel": "Cancel",
    "bookings.leaveReview": "Leave review",
    "bookings.offline": "Offline · showing cached data",
    "bookings.lastSync": "Last synced",
    "bookings.addNote": "Add a private note (visible only to you, offline)",
    "bookings.noteTitle": "Private note",
    "bookings.noteSub": "Kept on your device and available offline. Great for access codes, gate PINs, or client preferences.",
    "bookings.notePh": "e.g. Gate code 4287. Client prefers cash. Park in visitor lot.",
    "bookings.saveNote": "Save note",
    "bookings.markWorkDone": "I've finished the work",
    "bookings.awaitingClient": "Awaiting client confirmation",
    "bookings.confirmDone": "Confirm & review",
    "bookings.phoneHidden": "Phone hidden — reveal after confirmation",
    "bookings.revealPhone": "Reveal phone",
    "reveal.call": "Call",
    "reveal.noPhone": "No phone on file",
    "reveal.error": "Cannot reveal right now",
    // Phone verification banner (providers)
    "verifyPhone.bannerTitle": "Verify your phone",
    "verifyPhone.bannerSub": "You can't accept bookings until your phone is verified",
    "verifyPhone.action": "Verify",
    "verifyPhone.modalTitle": "Verify phone number",
    "verifyPhone.hintSend": "We'll send a 6-digit code to your phone via SMS.",
    "verifyPhone.hintEnter": "Enter the 6-digit code we sent you.",
    "verifyPhone.sendCode": "Send code",
    "verifyPhone.resend": "Resend",
    "verifyPhone.verify": "Verify",
    "verifyPhone.success": "Phone verified!",
    "verifyPhone.errSend": "Could not send code",
    "verifyPhone.errVerify": "Invalid or expired code",
    "verifyPhone.errCode": "Enter the 6-digit code",
    // Auth
    "auth.welcomeBack": "Welcome back",
    "auth.signInSub": "Sign in to your khedmaPro account",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.signInBtn": "Sign in",
    "auth.noAccount": "Don't have an account?",
    "auth.signUp": "Sign up",
    "auth.createAccount": "Create account",
    "auth.joinSub": "Join khedmaPro today",
    "auth.client": "Client",
    "auth.provider": "Provider",
    "auth.fullName": "Full name",
    "auth.phoneOptional": "Phone (optional)",
    "auth.phoneRequired": "Phone (required)",
    "auth.wilayaRequired": "Wilaya (required)",
    "auth.errPhoneProvider": "A valid Algerian mobile number is required for providers",
    "auth.errWilaya": "Please select your wilaya",
    "auth.cityOptional": "City (optional)",
    "auth.category": "Service category",
    "auth.bio": "Bio",
    "auth.bioPh": "Tell clients about your experience",
    "auth.hourlyRate": "Hourly rate (DZD)",
    "auth.taskRate": "Task rate (DZD)",
    "auth.trial": "3 months free, then 1000 DZD/month to stay listed.",
    "auth.createBtn": "Create account",
    "auth.haveAccount": "Already have an account?",
    "auth.errFill": "Please fill required fields",
    "auth.errCategory": "Please select a service category",
    // Review
    "review.title": "Leave a review",
    "review.prompt": "How was your experience?",
    "review.commentPh": "Tell others about your experience...",
    "review.submit": "Submit review",
    "review.needAccount": "Sign in required",
    "review.needAccountSub": "Create a free client account to leave a review.",
    // Profile
    "profile.title": "Profile",
    "profile.phone": "Phone",
    "profile.city": "City",
    "profile.signOut": "Sign out",
    "profile.guestTitle": "Sign in to unlock more",
    "profile.guestSub": "Create a free client account to track your bookings and leave reviews for the pros you hire.",
    "profile.guestCreate": "Create client account",
    "profile.guestSignIn": "Sign in",
    "profile.language": "Language",
    // Provider dashboard
    "dash.subDesc": "Here's how your business looks today.",
    "dash.subActive": "Subscription active",
    "dash.subTrial": "Free trial active",
    "dash.subDue": "Payment required",
    "dash.subDeact": "Profile deactivated",
    "dash.subActiveSub": "Renews in {days} days.",
    "dash.subTrialSub": "{days} days remaining. Then 1000 DZD/month.",
    "dash.subDueSub": "Pay 1000 DZD to keep your profile listed.",
    "dash.subDeactSub": "Contact support to reactivate.",
    "dash.pay": "Pay 1000 DZD",
    "dash.renew": "Renew now",
    "dash.earned": "DZD earned",
    "dash.completed": "Completed",
    "dash.upcoming": "Upcoming",
    "dash.pending": "Pending",
    "dash.yourRating": "Your rating",
    "dash.reviews": "reviews",
    "dash.recent": "Recent bookings",
    "dash.noBookings": "No bookings yet",
    "dash.noBookingsSub": "Clients will see your profile in the marketplace.",
    // Chat
    "chat.title": "Messages",
    "chat.empty": "No conversations yet",
    "chat.emptySub": "Start a chat from a provider profile.",
    "chat.placeholder": "Type a message…",
    "chat.send": "Send",
    "chat.safety": "Discuss job details safely — no phone numbers needed.",
    "chat.messageBtn": "Message",
    // Schedule
    "schedule.title": "My schedule",
    "schedule.workingHours": "Working hours",
    "schedule.breaks": "Breaks",
    "schedule.vacation": "Vacation days",
    "schedule.save": "Save schedule",
    "schedule.saved": "Schedule saved",
    "schedule.offlineHint": "Offline · showing cached data",
    "schedule.closed": "Closed",
    "schedule.setHours": "Set hours",
    "schedule.start": "Start",
    "schedule.end": "End",
    "schedule.tapDay": "Tap a day to add/remove a vacation",
    "schedule.langRestart": "Language applied. Restart the app for full RTL layout.",
    // Address
    "address.suggestions": "Suggestions",
    "address.searching": "Searching…",
    // Days
    "day.mon": "Monday",
    "day.tue": "Tuesday",
    "day.wed": "Wednesday",
    "day.thu": "Thursday",
    "day.fri": "Friday",
    "day.sat": "Saturday",
    "day.sun": "Sunday",
    // OTP
    "otp.title": "Continue with phone",
    "otp.subtitle": "We'll send you a 6-digit verification code.",
    "otp.phone": "Phone number",
    "otp.sendCode": "Send code",
    "otp.enterCode": "Enter the 6-digit code sent to",
    "otp.code": "Verification code",
    "otp.verify": "Verify",
    "otp.resend": "Resend code",
    "otp.resendIn": "Resend in {sec}s",
    "otp.wrongNumber": "Wrong number?",
    "otp.mockHint": "MOCK MODE — check the backend logs for the code.",
    "otp.iAm": "I am a",
    "otp.roleClient": "Client",
    "otp.roleProvider": "Service provider",
    "otp.errPhone": "Please enter a valid Algerian mobile number",
    "otp.errCode": "Please enter the 6-digit code",
    // Profile completion
    "profileC.title": "Complete your profile",
    "profileC.sub": "A few last details before we get started.",
    "profileC.save": "Save and continue",
    // Auth options
    "auth.orPhone": "or continue with phone",
    // Wilaya / location
    "wilaya.select": "Select wilaya",
    "wilaya.searchPh": "Search 58 wilayas…",
    "wilaya.mine": "My wilaya",
    "wilaya.crossOn": "Available across wilayas",
    "wilaya.crossOff": "Only my wilaya",
    "wilaya.baladiya": "Baladiya (municipality)",
    "wilaya.baladiyaPh": "e.g. Bab Ezzouar",
    "wilaya.filterAll": "All Algeria",
    // Booking type
    "booking.instant": "Instant booking",
    "booking.instantSub": "Book now at listed rate",
    "booking.quote": "Request quote",
    "booking.quoteSub": "Complex job — get a custom price",
    "booking.pinTitle": "Drop a pin at the service location",
    "booking.pinHint": "Tap the map or drag the marker to precisely mark the location.",
    "booking.pinConfirm": "Confirm location",
    "booking.locationSet": "Location pinned",
    // Report
    "report.title": "Report provider",
    "report.reason": "Reason",
    "report.details": "Details (optional)",
    "report.detailsPh": "Tell us what happened…",
    "report.submit": "Submit report",
    "report.submitted": "Report submitted. Thank you.",
    "report.reasons.noShow": "No-show / did not deliver",
    "report.reasons.poorQuality": "Poor quality",
    "report.reasons.priceGouging": "Overcharged",
    "report.reasons.unsafe": "Unsafe behavior",
    "report.reasons.fraud": "Fraud / scam",
    "report.reasons.other": "Other",
    "report.needAccount": "Sign in required to report",
    // Portfolio
    "portfolio.title": "Portfolio",
    "portfolio.empty": "No photos yet",
    "portfolio.add": "Add photo",
    "portfolio.compressing": "Compressing…",
    "portfolio.limit": "Up to 20 photos",
    "portfolio.compressing": "Compressing…",
    "portfolio.compressedInfo": "Compressed {before} → {after} ({passes} pass)",
    "portfolio.cover": "Cover",
    "portfolio.setCover": "Set as cover",
    "portfolio.isCover": "This is your cover photo",
    "portfolio.editorTitle": "Edit photo",
    "portfolio.caption": "Caption",
    "portfolio.captionPh": "e.g. Kitchen repaint · Bab Ezzouar, June 2026",
    "portfolio.tags": "Category tags",
    "portfolio.save": "Save",
    "portfolio.tag_before": "Before",
    "portfolio.tag_after": "After",
    "portfolio.tag_residential": "Residential",
    "portfolio.tag_commercial": "Commercial",
    "portfolio.tag_interior": "Interior",
    "portfolio.tag_exterior": "Exterior",
    "portfolio.tag_detail": "Detail",
    "portfolio.tag_custom": "Custom",
    // Verification
    "verify.title": "Trust & verification",
    "verify.status.unverified": "Not verified",
    "verify.status.pending": "Under review",
    "verify.status.verified": "Verified",
    "verify.status.rejected": "Rejected",
    "verify.desc.unverified": "Get a verified badge on your profile by submitting your ID and (optionally) certifications. Verified providers win more bookings.",
    "verify.desc.pending": "Our team is reviewing your documents. Typical turnaround is 1–3 business days.",
    "verify.desc.verified": "You're verified! Clients see the trust badge next to your name.",
    "verify.desc.rejected": "Your submission was rejected. Please review the reason below and resubmit.",
    "verify.submitted": "Submitted {n} document(s) — awaiting review",
    "verify.startCta": "Start verification",
    "verify.resubmit": "Resubmit",
    "verify.submitCta": "Submit for review",
    "verify.uploaderSub": "Upload clear photos of the required documents. Images are compressed locally on your device before upload.",
    "verify.required": "REQUIRED",
    "verify.compressing": "Compressing…",
    "verify.upload": "Upload",
    "verify.idRecto": "National ID — front",
    "verify.idRectoHint": "Ensure name, photo, and ID number are readable.",
    "verify.idVerso": "National ID — back",
    "verify.idVersoHint": "Both sides help us confirm your identity.",
    "verify.certification": "Professional certification",
    "verify.certificationHint": "Trade certificate, diploma or license (optional).",
    "verify.background": "Background check",
    "verify.backgroundHint": "Casier Judiciaire or equivalent (optional).",
    "verify.badgeShort": "Verified",
    // Admin
    "admin.title": "Verification queue",
    "admin.empty": "No pending verifications 🎉",
    "admin.forbidden": "Admin access required",
    "admin.goHome": "Back to app",
    "admin.submitted": "Submitted",
    "admin.approve": "Approve",
    "admin.reject": "Reject",
    "admin.rejectTitle": "Reject verification",
    "admin.rejectSub": "The provider will see this reason and can resubmit new documents.",
    "admin.rejectPh": "e.g. ID photo is blurry — please reupload with better lighting.",
    "admin.unnamed": "Unnamed provider",
    "common.retry": "Retry",
    // Admin flags
    "flags.title": "Flagged providers",
    "flags.empty": "No flagged providers 🎉",
    "flags.bannerSub": "{n} provider(s) auto-flagged for review",
    "flags.reason": "Reason",
    "flags.flaggedAt": "Flagged at",
    "flags.completion": "Completion rate",
    "flags.clear": "Clear flag & reactivate",
    "flags.confirmTitle": "Clear this flag?",
    "flags.confirmSub": "The provider will be reactivated and the search penalty removed.",
    "flags.section": "Auto-flagged",
    "flags.sectionSub": "Providers auto-flagged for review",
    // Account settings
    "account.section": "Account",
    "account.subscription": "Subscription",
    "account.subActive": "Active subscription",
    "account.subTrial": "Free trial",
    "account.subDue": "Payment due",
    "account.subDeact": "Deactivated",
    "account.subDeleted": "Deleted",
    "account.subManual": "Manually deactivated",
    "account.daysLeftTrial": "{days} days left in trial",
    "account.daysLeftActive": "Renews in {days} days",
    "account.dueNow": "Pay 1000 DZD now to keep your profile listed.",
    "account.willAutoDelete": "Profile will be permanently deleted after 12 unpaid months.",
    "account.payNow": "Pay 1000 DZD",
    "account.paying": "Processing…",
    "account.paySuccess": "Payment received — thank you!",
    "account.dangerZone": "Danger zone",
    "account.deactivate": "Deactivate account",
    "account.deactivateSub": "Temporarily hide your profile. You can reactivate anytime by signing in and tapping Reactivate.",
    "account.reactivate": "Reactivate account",
    "account.reactivateSub": "Restore your account and make your profile visible again.",
    "account.delete": "Delete account",
    "account.deleteSub": "Permanently remove your account. This action cannot be undone.",
    "account.switchRole": "Switch role / Back to start",
    "account.switchRoleSub": "Sign out and return to the initial screen to pick a different role.",
    "account.confirmDeactivate": "Deactivate your account?",
    "account.confirmDeactivateSub": "Your profile will be hidden until you reactivate.",
    "account.confirmDelete": "Delete your account?",
    "account.confirmDeleteSub": "This is permanent. Your bookings history, reviews and messages will be hidden and you won't be able to log back in.",
    "account.confirmReactivate": "Reactivate account?",
    "account.confirmReactivateSub": "Your profile will become visible to clients again.",
    "account.cancel": "Cancel",
    "account.confirm": "Confirm",
    "account.deleted": "Account deleted",
    "account.deletedSub": "Your account has been permanently removed.",
    "account.deactivated": "Account deactivated",
    "account.reactivated": "Account reactivated",
    "account.deactBanner": "Your account is currently deactivated. Reactivate to appear in search again.",
    "account.mockPay": "Payment gateway is mocked in this build.",
  },
  fr: {
    "app.name": "khedmaPro",
    "onboarding.title": "Des pros de confiance\nà portée de main.",
    "onboarding.subtitle": "Parcourez des prestataires vérifiés instantanément — pas besoin de compte pour chercher ou réserver.",
    "onboarding.browse": "Parcourir les services",
    "onboarding.iamProvider": "Je suis un prestataire",
    // Landing
    "landing.pilotBadge": "CONÇU POUR L'ALGÉRIE",
    "landing.heroTitle": "Les pros de confiance\nde votre ville, en un clic.",
    "landing.heroSubtitle": "Plombiers, électriciens, ménage, cours particuliers et plus — vérifiés, notés, disponibles dans les 58 wilayas.",
    "landing.f1Title": "Pros vérifiés",
    "landing.f1Sub": "Identité contrôlée pour votre tranquillité.",
    "landing.f2Title": "Réservation directe",
    "landing.f2Sub": "Au tarif affiché ou sur devis personnalisé.",
    "landing.f3Title": "Chat intégré",
    "landing.f3Sub": "Discutez avant de réserver. Numéros privés.",
    "landing.f4Title": "Avis réels",
    "landing.f4Sub": "De clients qui ont vraiment réservé.",
    "landing.trustWilayas": "Wilayas",
    "landing.trustLangs": "Langues",
    "landing.trustTrial": "Jours d'essai",
    "onboarding.haveAccount": "Vous avez un compte prestataire ?",
    "onboarding.signIn": "Se connecter",
    "home.helloGuest": "Trouver un pro",
    "home.hello": "Bonjour",
    "home.searchPlaceholder": "Rechercher un prestataire, un service...",
    "home.categoryFilter": "Catégorie",
    "home.scope.filterBy": "Distance",
    "filters.title": "Filtres",
    "filters.distance": "Distance",
    "filters.category": "Catégorie",
    "filters.verifiedOnly": "Prestataires vérifiés uniquement",
    "filters.verifiedOnlySub": "N'afficher que les prestataires avec identité vérifiée.",
    "filters.apply": "Appliquer",
    "filters.reset": "Réinitialiser",
    "home.promoBadge": "NOUVEAU",
    "home.promoTitle": "Réservez des pros vérifiés\ndans toute l'Algérie",
    "home.promoSub": "Prestataires de confiance, tarifs transparents.",
    "home.categories": "Catégories",
    "home.all": "Tous",
    "home.topRated": "Les mieux notés",
    "home.allProviders": "Tous les prestataires",
    "home.noResults": "Aucun prestataire trouvé",
    "home.headerSignIn": "Se connecter",
    "home.scope.km": "Dans un rayon de {km} km",
    "home.scope.wilaya": "Par wilaya",
    "home.scope.country": "Toute l'Algérie",
    "home.distanceKm": "à {km} km",
    "home.distanceMeters": "à {m} m",
    "home.locationDenied": "Localisation désactivée — affichage de votre wilaya. Activez la localisation pour rechercher par rayon.",
    "cat.plumbing": "Plomberie",
    "cat.electrical": "Électricité",
    "cat.cleaning": "Nettoyage",
    "cat.carpentry": "Menuiserie",
    "cat.painting": "Peinture",
    "cat.landscaping": "Jardinage",
    "cat.it_support": "Support IT",
    "cat.admin_consulting": "Consultants administratifs",
    "cat.education": "Éducation (cours particuliers)",
    "cat.photography": "Photographie",
    "cat.moving": "Déménagement",
    "provider.verified": "Vérifié",
    "provider.reviews": "Avis",
    "provider.noReviews": "Aucun avis pour l'instant. Soyez le premier !",
    "provider.perHour": "DZD / heure",
    "provider.perTask": "DZD / tâche",
    "provider.requestBooking": "Réserver",
    "provider.writeReview": "Laisser un avis",
    "booking.title": "Demander une réservation",
    "booking.selectDate": "Choisir la date",
    "booking.selectTime": "Choisir l'heure",
    "booking.rateType": "Type de tarif",
    "booking.hourly": "Horaire",
    "booking.task": "Tâche",
    "booking.hours": "Heures estimées",
    "booking.description": "Description de la tâche",
    "booking.descriptionPh": "Décrivez ce que vous avez besoin...",
    "booking.address": "Adresse",
    "booking.addressPh": "Rue, ville",
    "booking.yourInfo": "Vos coordonnées",
    "booking.name": "Nom complet",
    "booking.phone": "Téléphone",
    "booking.email": "Email (optionnel)",
    "booking.total": "Total estimé",
    "booking.confirm": "Confirmer",
    "booking.success": "Réservation envoyée !",
    "booking.successSub": "répondra bientôt.",
    "booking.viewBookings": "Voir mes réservations",
    "booking.done": "Terminé",
    "booking.errFill": "Veuillez ajouter la description et l'adresse",
    "booking.errGuest": "Veuillez saisir votre nom et téléphone",
    "bookings.title": "Mes réservations",
    "bookings.all": "Toutes",
    "bookings.pending": "En attente",
    "bookings.confirmed": "Confirmées",
    "bookings.completed": "Terminées",
    "bookings.empty": "Aucune réservation",
    "bookings.accept": "Accepter",
    "bookings.decline": "Refuser",
    "bookings.markComplete": "Marquer terminée",
    "bookings.cancel": "Annuler",
    "bookings.leaveReview": "Laisser un avis",
    "bookings.offline": "Hors ligne · données en cache",
    "bookings.lastSync": "Dernière synchro",
    "bookings.addNote": "Ajouter une note privée (visible uniquement par vous, hors ligne)",
    "bookings.noteTitle": "Note privée",
    "bookings.noteSub": "Conservée sur votre appareil et disponible hors ligne. Idéale pour codes d'accès, PIN de portail ou préférences client.",
    "bookings.notePh": "ex. Code portail 4287. Client préfère espèces. Parking visiteurs.",
    "bookings.saveNote": "Enregistrer la note",
    "bookings.markWorkDone": "J'ai terminé le travail",
    "bookings.awaitingClient": "En attente de confirmation client",
    "bookings.confirmDone": "Confirmer et noter",
    "bookings.phoneHidden": "Téléphone masqué — visible après confirmation",
    "bookings.revealPhone": "Afficher le téléphone",
    "reveal.call": "Appeler",
    "reveal.noPhone": "Aucun téléphone enregistré",
    "reveal.error": "Impossible d'afficher pour le moment",
    // Phone verification banner (providers)
    "verifyPhone.bannerTitle": "Vérifiez votre téléphone",
    "verifyPhone.bannerSub": "Vous ne pouvez pas accepter de réservations sans vérifier votre téléphone",
    "verifyPhone.action": "Vérifier",
    "verifyPhone.modalTitle": "Vérifier le téléphone",
    "verifyPhone.hintSend": "Nous vous enverrons un code à 6 chiffres par SMS.",
    "verifyPhone.hintEnter": "Saisissez le code à 6 chiffres reçu.",
    "verifyPhone.sendCode": "Envoyer le code",
    "verifyPhone.resend": "Renvoyer",
    "verifyPhone.verify": "Vérifier",
    "verifyPhone.success": "Téléphone vérifié !",
    "verifyPhone.errSend": "Impossible d'envoyer le code",
    "verifyPhone.errVerify": "Code invalide ou expiré",
    "verifyPhone.errCode": "Saisissez le code à 6 chiffres",
    "auth.welcomeBack": "Bon retour",
    "auth.signInSub": "Connectez-vous à votre compte khedmaPro",
    "auth.email": "Email",
    "auth.password": "Mot de passe",
    "auth.signInBtn": "Se connecter",
    "auth.noAccount": "Pas de compte ?",
    "auth.signUp": "S'inscrire",
    "auth.createAccount": "Créer un compte",
    "auth.joinSub": "Rejoignez khedmaPro aujourd'hui",
    "auth.client": "Client",
    "auth.provider": "Prestataire",
    "auth.fullName": "Nom complet",
    "auth.phoneOptional": "Téléphone (optionnel)",
    "auth.phoneRequired": "Téléphone (obligatoire)",
    "auth.wilayaRequired": "Wilaya (obligatoire)",
    "auth.errPhoneProvider": "Un numéro algérien valide est obligatoire pour les prestataires",
    "auth.errWilaya": "Veuillez choisir votre wilaya",
    "auth.cityOptional": "Ville (optionnel)",
    "auth.category": "Catégorie de service",
    "auth.bio": "Bio",
    "auth.bioPh": "Parlez aux clients de votre expérience",
    "auth.hourlyRate": "Tarif horaire (DZD)",
    "auth.taskRate": "Tarif à la tâche (DZD)",
    "auth.trial": "3 mois gratuits, puis 1000 DZD/mois pour rester listé.",
    "auth.createBtn": "Créer un compte",
    "auth.haveAccount": "Vous avez déjà un compte ?",
    "auth.errFill": "Veuillez remplir les champs requis",
    "auth.errCategory": "Veuillez choisir une catégorie",
    "review.title": "Laisser un avis",
    "review.prompt": "Comment était votre expérience ?",
    "review.commentPh": "Partagez votre expérience...",
    "review.submit": "Envoyer l'avis",
    "review.needAccount": "Connexion requise",
    "review.needAccountSub": "Créez un compte client gratuit pour laisser un avis.",
    "profile.title": "Profil",
    "profile.phone": "Téléphone",
    "profile.city": "Ville",
    "profile.signOut": "Se déconnecter",
    "profile.guestTitle": "Connectez-vous pour plus",
    "profile.guestSub": "Créez un compte client gratuit pour suivre vos réservations et laisser des avis.",
    "profile.guestCreate": "Créer un compte client",
    "profile.guestSignIn": "Se connecter",
    "profile.language": "Langue",
    "dash.subDesc": "Voici votre activité aujourd'hui.",
    "dash.subActive": "Abonnement actif",
    "dash.subTrial": "Essai gratuit actif",
    "dash.subDue": "Paiement requis",
    "dash.subDeact": "Profil désactivé",
    "dash.subActiveSub": "Renouvellement dans {days} jours.",
    "dash.subTrialSub": "{days} jours restants. Ensuite 1000 DZD/mois.",
    "dash.subDueSub": "Payez 1000 DZD pour rester listé.",
    "dash.subDeactSub": "Contactez le support pour réactiver.",
    "dash.pay": "Payer 1000 DZD",
    "dash.renew": "Renouveler",
    "dash.earned": "DZD gagnés",
    "dash.completed": "Terminées",
    "dash.upcoming": "À venir",
    "dash.pending": "En attente",
    "dash.yourRating": "Votre note",
    "dash.reviews": "avis",
    "dash.recent": "Réservations récentes",
    "dash.noBookings": "Aucune réservation",
    "dash.noBookingsSub": "Les clients verront votre profil dans la marketplace.",
    "chat.title": "Messages",
    "chat.empty": "Aucune conversation",
    "chat.emptySub": "Commencez une discussion depuis un profil de prestataire.",
    "chat.placeholder": "Écrire un message…",
    "chat.send": "Envoyer",
    "chat.safety": "Discutez en toute sécurité — pas besoin de numéro personnel.",
    "chat.messageBtn": "Message",
    "schedule.title": "Mon planning",
    "schedule.workingHours": "Heures d'ouverture",
    "schedule.breaks": "Pauses",
    "schedule.vacation": "Jours de congé",
    "schedule.save": "Enregistrer",
    "schedule.saved": "Planning enregistré",
    "schedule.offlineHint": "Hors ligne · données en cache",
    "schedule.closed": "Fermé",
    "schedule.setHours": "Définir",
    "schedule.start": "Début",
    "schedule.end": "Fin",
    "schedule.tapDay": "Touchez un jour pour ajouter/retirer un congé",
    "schedule.langRestart": "Langue appliquée. Redémarrez l'app pour le RTL complet.",
    "address.suggestions": "Suggestions",
    "address.searching": "Recherche…",
    "day.mon": "Lundi",
    "day.tue": "Mardi",
    "day.wed": "Mercredi",
    "day.thu": "Jeudi",
    "day.fri": "Vendredi",
    "day.sat": "Samedi",
    "day.sun": "Dimanche",
    "otp.title": "Continuer avec votre téléphone",
    "otp.subtitle": "Nous vous enverrons un code à 6 chiffres.",
    "otp.phone": "Numéro de téléphone",
    "otp.sendCode": "Envoyer le code",
    "otp.enterCode": "Entrez le code à 6 chiffres envoyé à",
    "otp.code": "Code de vérification",
    "otp.verify": "Vérifier",
    "otp.resend": "Renvoyer",
    "otp.resendIn": "Renvoyer dans {sec}s",
    "otp.wrongNumber": "Mauvais numéro ?",
    "otp.mockHint": "MODE TEST — consultez les logs du backend pour le code.",
    "otp.iAm": "Je suis un",
    "otp.roleClient": "Client",
    "otp.roleProvider": "Prestataire",
    "otp.errPhone": "Numéro algérien invalide",
    "otp.errCode": "Entrez le code à 6 chiffres",
    "profileC.title": "Complétez votre profil",
    "profileC.sub": "Quelques derniers détails avant de commencer.",
    "profileC.save": "Enregistrer et continuer",
    "auth.orPhone": "ou continuer avec votre téléphone",
    "wilaya.select": "Choisir la wilaya",
    "wilaya.searchPh": "Rechercher parmi 58 wilayas…",
    "wilaya.mine": "Ma wilaya",
    "wilaya.crossOn": "Disponible dans toutes les wilayas",
    "wilaya.crossOff": "Uniquement ma wilaya",
    "wilaya.baladiya": "Baladiya (commune)",
    "wilaya.baladiyaPh": "ex. Bab Ezzouar",
    "wilaya.filterAll": "Toute l'Algérie",
    "booking.instant": "Réservation instantanée",
    "booking.instantSub": "Au tarif affiché",
    "booking.quote": "Demander un devis",
    "booking.quoteSub": "Travail complexe — prix sur mesure",
    "booking.pinTitle": "Placez une épingle à l'emplacement",
    "booking.pinHint": "Touchez la carte ou déplacez le marqueur pour indiquer précisément le lieu.",
    "booking.pinConfirm": "Confirmer l'emplacement",
    "booking.locationSet": "Lieu épinglé",
    "report.title": "Signaler ce prestataire",
    "report.reason": "Motif",
    "report.details": "Détails (optionnel)",
    "report.detailsPh": "Dites-nous ce qui s'est passé…",
    "report.submit": "Envoyer le signalement",
    "report.submitted": "Signalement envoyé. Merci.",
    "report.reasons.noShow": "Absent / non-livraison",
    "report.reasons.poorQuality": "Mauvaise qualité",
    "report.reasons.priceGouging": "Facturation excessive",
    "report.reasons.unsafe": "Comportement dangereux",
    "report.reasons.fraud": "Fraude / arnaque",
    "report.reasons.other": "Autre",
    "report.needAccount": "Connexion requise pour signaler",
    "portfolio.title": "Portfolio",
    "portfolio.empty": "Aucune photo",
    "portfolio.add": "Ajouter",
    "portfolio.compressing": "Compression…",
    "portfolio.limit": "Jusqu'à 20 photos",
    "portfolio.compressing": "Compression…",
    "portfolio.compressedInfo": "Compressé {before} → {after} ({passes} passe)",
    "portfolio.cover": "Couverture",
    "portfolio.setCover": "Définir comme couverture",
    "portfolio.isCover": "C'est votre photo de couverture",
    "portfolio.editorTitle": "Modifier la photo",
    "portfolio.caption": "Légende",
    "portfolio.captionPh": "ex. Peinture cuisine · Bab Ezzouar, juin 2026",
    "portfolio.tags": "Catégories",
    "portfolio.save": "Enregistrer",
    "portfolio.tag_before": "Avant",
    "portfolio.tag_after": "Après",
    "portfolio.tag_residential": "Résidentiel",
    "portfolio.tag_commercial": "Commercial",
    "portfolio.tag_interior": "Intérieur",
    "portfolio.tag_exterior": "Extérieur",
    "portfolio.tag_detail": "Détail",
    "portfolio.tag_custom": "Sur mesure",
    // Verification
    "verify.title": "Confiance & vérification",
    "verify.status.unverified": "Non vérifié",
    "verify.status.pending": "En cours d'examen",
    "verify.status.verified": "Vérifié",
    "verify.status.rejected": "Rejeté",
    "verify.desc.unverified": "Obtenez un badge « Vérifié » sur votre profil en soumettant votre pièce d'identité (et éventuellement vos certifications). Les prestataires vérifiés obtiennent plus de réservations.",
    "verify.desc.pending": "Notre équipe examine vos documents. Le délai habituel est de 1 à 3 jours ouvrés.",
    "verify.desc.verified": "Vous êtes vérifié ! Un badge de confiance apparaît à côté de votre nom.",
    "verify.desc.rejected": "Votre soumission a été rejetée. Consultez la raison ci-dessous et soumettez à nouveau.",
    "verify.submitted": "{n} document(s) envoyé(s) — en attente de vérification",
    "verify.startCta": "Démarrer la vérification",
    "verify.resubmit": "Renvoyer",
    "verify.submitCta": "Soumettre pour examen",
    "verify.uploaderSub": "Téléchargez des photos nettes des documents requis. Les images sont compressées localement sur votre appareil avant l'envoi.",
    "verify.required": "REQUIS",
    "verify.compressing": "Compression…",
    "verify.upload": "Télécharger",
    "verify.idRecto": "Carte d'identité — recto",
    "verify.idRectoHint": "Nom, photo et numéro doivent être lisibles.",
    "verify.idVerso": "Carte d'identité — verso",
    "verify.idVersoHint": "Les deux faces nous aident à confirmer votre identité.",
    "verify.certification": "Certification professionnelle",
    "verify.certificationHint": "Certificat de métier, diplôme ou licence (facultatif).",
    "verify.background": "Casier judiciaire",
    "verify.backgroundHint": "Extrait du casier judiciaire ou équivalent (facultatif).",
    "verify.badgeShort": "Vérifié",
    // Admin
    "admin.title": "File d'attente de vérification",
    "admin.empty": "Aucune vérification en attente 🎉",
    "admin.forbidden": "Accès administrateur requis",
    "admin.goHome": "Retour à l'app",
    "admin.submitted": "Soumis",
    "admin.approve": "Approuver",
    "admin.reject": "Rejeter",
    "admin.rejectTitle": "Rejeter la vérification",
    "admin.rejectSub": "Le prestataire verra cette raison et pourra soumettre de nouveaux documents.",
    "admin.rejectPh": "ex. Photo de la carte d'identité floue — merci de la reprendre avec un meilleur éclairage.",
    "admin.unnamed": "Prestataire sans nom",
    "common.retry": "Réessayer",
    // Admin flags
    "flags.title": "Prestataires signalés",
    "flags.empty": "Aucun prestataire signalé 🎉",
    "flags.bannerSub": "{n} prestataire(s) signalé(s) automatiquement",
    "flags.reason": "Raison",
    "flags.flaggedAt": "Signalé le",
    "flags.completion": "Taux de complétion",
    "flags.clear": "Effacer le signalement & réactiver",
    "flags.confirmTitle": "Effacer ce signalement ?",
    "flags.confirmSub": "Le prestataire sera réactivé et la pénalité de recherche supprimée.",
    "flags.section": "Signalés",
    "flags.sectionSub": "Prestataires signalés automatiquement",
    // Account settings
    "account.section": "Compte",
    "account.subscription": "Abonnement",
    "account.subActive": "Abonnement actif",
    "account.subTrial": "Essai gratuit",
    "account.subDue": "Paiement requis",
    "account.subDeact": "Désactivé",
    "account.subDeleted": "Supprimé",
    "account.subManual": "Désactivé manuellement",
    "account.daysLeftTrial": "{days} jours restants d'essai",
    "account.daysLeftActive": "Renouvellement dans {days} jours",
    "account.dueNow": "Payez 1000 DZD maintenant pour rester listé.",
    "account.willAutoDelete": "Le profil sera supprimé après 12 mois impayés.",
    "account.payNow": "Payer 1000 DZD",
    "account.paying": "Traitement…",
    "account.paySuccess": "Paiement reçu — merci !",
    "account.dangerZone": "Zone sensible",
    "account.deactivate": "Désactiver le compte",
    "account.deactivateSub": "Masquer temporairement votre profil. Vous pouvez le réactiver à tout moment.",
    "account.reactivate": "Réactiver le compte",
    "account.reactivateSub": "Restaurer votre compte et rendre le profil visible à nouveau.",
    "account.delete": "Supprimer le compte",
    "account.deleteSub": "Suppression permanente. Cette action est irréversible.",
    "account.switchRole": "Changer de rôle / Retour",
    "account.switchRoleSub": "Se déconnecter et revenir à l'écran d'accueil pour choisir un autre rôle.",
    "account.confirmDeactivate": "Désactiver le compte ?",
    "account.confirmDeactivateSub": "Votre profil sera masqué jusqu'à réactivation.",
    "account.confirmDelete": "Supprimer le compte ?",
    "account.confirmDeleteSub": "Action permanente. Votre historique, avis et messages seront masqués et vous ne pourrez plus vous connecter.",
    "account.confirmReactivate": "Réactiver le compte ?",
    "account.confirmReactivateSub": "Votre profil sera à nouveau visible pour les clients.",
    "account.cancel": "Annuler",
    "account.confirm": "Confirmer",
    "account.deleted": "Compte supprimé",
    "account.deletedSub": "Votre compte a été supprimé de manière permanente.",
    "account.deactivated": "Compte désactivé",
    "account.reactivated": "Compte réactivé",
    "account.deactBanner": "Votre compte est actuellement désactivé. Réactivez-le pour réapparaître dans la recherche.",
    "account.mockPay": "La passerelle de paiement est simulée dans cette version.",
  },
  ar: {
    "app.name": "خدمة برو",
    "onboarding.title": "محترفون موثوقون\nفي متناول يدك.",
    "onboarding.subtitle": "تصفح مقدمي الخدمات المعتمدين فورًا — لا حاجة لإنشاء حساب للبحث أو الحجز.",
    // Landing
    "landing.pilotBadge": "صُنع للجزائر",
    "landing.heroTitle": "المحترفون الموثوقون\nفي مدينتك، بضغطة واحدة.",
    "landing.heroSubtitle": "احجز سباكين، كهربائيين، منظفين، مدرسين وأكثر — موثقون، مقيّمون، متاحون في 58 ولاية.",
    "landing.f1Title": "محترفون موثقون",
    "landing.f1Sub": "هوية مُتحقَّق منها لراحة بالك.",
    "landing.f2Title": "حجز فوري",
    "landing.f2Sub": "بالسعر المعلن أو عرض سعر مخصص.",
    "landing.f3Title": "محادثة مدمجة",
    "landing.f3Sub": "تواصل قبل الحجز. الأرقام تبقى خاصة.",
    "landing.f4Title": "تقييمات حقيقية",
    "landing.f4Sub": "من عملاء حجزوا فعلًا.",
    "landing.trustWilayas": "ولاية",
    "landing.trustLangs": "لغات",
    "landing.trustTrial": "يوم تجربة",
    "onboarding.browse": "تصفح الخدمات",
    "onboarding.iamProvider": "أنا مقدم خدمة",
    "onboarding.haveAccount": "لديك حساب مقدم خدمة؟",
    "onboarding.signIn": "تسجيل الدخول",
    "home.helloGuest": "ابحث عن محترف",
    "home.hello": "مرحبًا",
    "home.searchPlaceholder": "ابحث عن مقدم خدمة أو خدمة...",
    "home.categoryFilter": "الفئة",
    "home.scope.filterBy": "المسافة",
    "filters.title": "الفلاتر",
    "filters.distance": "المسافة",
    "filters.category": "الفئة",
    "filters.verifiedOnly": "المزوّدون الموثّقون فقط",
    "filters.verifiedOnlySub": "إظهار المزوّدين ذوي الهوية الموثّقة فقط.",
    "filters.apply": "تطبيق",
    "filters.reset": "إعادة تعيين",
    "home.promoBadge": "جديد",
    "home.promoTitle": "احجز محترفين موثوقين\nفي جميع أنحاء الجزائر",
    "home.promoSub": "مقدمو خدمات موثوقون بأسعار شفافة.",
    "home.categories": "الفئات",
    "home.all": "الكل",
    "home.topRated": "الأعلى تقييمًا",
    "home.allProviders": "جميع مقدمي الخدمات",
    "home.noResults": "لا يوجد مقدمو خدمات",
    "home.headerSignIn": "دخول",
    "home.scope.km": "ضمن {km} كم",
    "home.scope.wilaya": "حسب الولاية",
    "home.scope.country": "كل الجزائر",
    "home.distanceKm": "على بُعد {km} كم",
    "home.distanceMeters": "على بُعد {m} م",
    "home.locationDenied": "الموقع معطّل — يتم العرض حسب ولايتك. فعّل الموقع للبحث حسب نصف القطر.",
    "cat.plumbing": "سباكة",
    "cat.electrical": "كهرباء",
    "cat.cleaning": "تنظيف",
    "cat.carpentry": "نجارة",
    "cat.painting": "دهان",
    "cat.landscaping": "بستنة",
    "cat.it_support": "دعم تقني",
    "cat.admin_consulting": "استشاريون إداريون",
    "cat.education": "التعليم (دروس خصوصية)",
    "cat.photography": "تصوير",
    "cat.moving": "نقل الأثاث",
    "provider.verified": "موثوق",
    "provider.reviews": "التقييمات",
    "provider.noReviews": "لا توجد تقييمات بعد. كن الأول!",
    "provider.perHour": "دج / ساعة",
    "provider.perTask": "دج / مهمة",
    "provider.requestBooking": "طلب حجز",
    "provider.writeReview": "اكتب تقييمًا",
    "booking.title": "طلب حجز",
    "booking.selectDate": "اختر التاريخ",
    "booking.selectTime": "اختر الوقت",
    "booking.rateType": "نوع التسعير",
    "booking.hourly": "بالساعة",
    "booking.task": "بالمهمة",
    "booking.hours": "الساعات المقدرة",
    "booking.description": "وصف المهمة",
    "booking.descriptionPh": "صف ما تحتاج القيام به...",
    "booking.address": "العنوان",
    "booking.addressPh": "الشارع، المدينة",
    "booking.yourInfo": "بيانات التواصل",
    "booking.name": "الاسم الكامل",
    "booking.phone": "الهاتف",
    "booking.email": "البريد الإلكتروني (اختياري)",
    "booking.total": "الإجمالي المقدر",
    "booking.confirm": "تأكيد",
    "booking.success": "تم إرسال الطلب!",
    "booking.successSub": "سيرد عليك قريبًا.",
    "booking.viewBookings": "عرض الحجوزات",
    "booking.done": "تم",
    "booking.errFill": "يرجى إضافة وصف المهمة والعنوان",
    "booking.errGuest": "يرجى إدخال اسمك ورقم هاتفك",
    "bookings.title": "حجوزاتي",
    "bookings.all": "الكل",
    "bookings.pending": "قيد الانتظار",
    "bookings.confirmed": "مؤكدة",
    "bookings.completed": "منجزة",
    "bookings.empty": "لا توجد حجوزات",
    "bookings.accept": "قبول",
    "bookings.decline": "رفض",
    "bookings.markComplete": "تحديد كمنجز",
    "bookings.cancel": "إلغاء",
    "bookings.leaveReview": "اكتب تقييمًا",
    "bookings.offline": "غير متصل · عرض البيانات المخبأة",
    "bookings.lastSync": "آخر مزامنة",
    "bookings.addNote": "أضف ملاحظة خاصة (تظهر لك فقط، وتعمل دون إنترنت)",
    "bookings.noteTitle": "ملاحظة خاصة",
    "bookings.noteSub": "تُحفظ على جهازك وتبقى متاحة دون إنترنت. مثالية لرموز الدخول أو تفضيلات الزبون.",
    "bookings.notePh": "مثال: رمز البوابة 4287. يفضل الدفع نقدًا. موقف الزوار.",
    "bookings.saveNote": "حفظ الملاحظة",
    "bookings.markWorkDone": "لقد أنهيت العمل",
    "bookings.awaitingClient": "بانتظار تأكيد الزبون",
    "bookings.confirmDone": "أكّد وقيّم",
    "bookings.phoneHidden": "الرقم مخفي — يظهر بعد التأكيد",
    "bookings.revealPhone": "إظهار الرقم",
    "reveal.call": "اتصال",
    "reveal.noPhone": "لا يوجد رقم مسجَّل",
    "reveal.error": "لا يمكن الإظهار الآن",
    // Phone verification banner (providers)
    "verifyPhone.bannerTitle": "تحقق من هاتفك",
    "verifyPhone.bannerSub": "لا يمكنك قبول الحجوزات حتى يتم التحقق من رقمك",
    "verifyPhone.action": "تحقق",
    "verifyPhone.modalTitle": "تحقق من رقم الهاتف",
    "verifyPhone.hintSend": "سنرسل رمزًا مكونًا من 6 أرقام عبر SMS.",
    "verifyPhone.hintEnter": "أدخل الرمز المكون من 6 أرقام.",
    "verifyPhone.sendCode": "إرسال الرمز",
    "verifyPhone.resend": "إعادة الإرسال",
    "verifyPhone.verify": "تحقق",
    "verifyPhone.success": "تم التحقق من الهاتف!",
    "verifyPhone.errSend": "تعذر إرسال الرمز",
    "verifyPhone.errVerify": "رمز غير صالح أو منتهي",
    "verifyPhone.errCode": "أدخل الرمز المكون من 6 أرقام",
    "auth.welcomeBack": "مرحبًا بعودتك",
    "auth.signInSub": "سجّل الدخول إلى حسابك في خدمة برو",
    "auth.email": "البريد الإلكتروني",
    "auth.password": "كلمة المرور",
    "auth.signInBtn": "تسجيل الدخول",
    "auth.noAccount": "ليس لديك حساب؟",
    "auth.signUp": "أنشئ حسابًا",
    "auth.createAccount": "إنشاء حساب",
    "auth.joinSub": "انضم إلى خدمة برو اليوم",
    "auth.client": "زبون",
    "auth.provider": "مقدم خدمة",
    "auth.fullName": "الاسم الكامل",
    "auth.phoneOptional": "الهاتف (اختياري)",
    "auth.phoneRequired": "الهاتف (مطلوب)",
    "auth.wilayaRequired": "الولاية (مطلوبة)",
    "auth.errPhoneProvider": "مطلوب رقم هاتف جزائري صالح لمقدمي الخدمة",
    "auth.errWilaya": "يرجى اختيار ولايتك",
    "auth.cityOptional": "المدينة (اختياري)",
    "auth.category": "فئة الخدمة",
    "auth.bio": "نبذة",
    "auth.bioPh": "أخبر العملاء عن خبرتك",
    "auth.hourlyRate": "التعرفة بالساعة (دج)",
    "auth.taskRate": "التعرفة بالمهمة (دج)",
    "auth.trial": "3 أشهر مجانًا، ثم 1000 دج/شهر للبقاء مدرجًا.",
    "auth.createBtn": "إنشاء الحساب",
    "auth.haveAccount": "لديك حساب بالفعل؟",
    "auth.errFill": "يرجى ملء الحقول المطلوبة",
    "auth.errCategory": "يرجى اختيار فئة",
    "review.title": "اكتب تقييمًا",
    "review.prompt": "كيف كانت تجربتك؟",
    "review.commentPh": "شارك تجربتك مع الآخرين...",
    "review.submit": "إرسال التقييم",
    "review.needAccount": "تسجيل الدخول مطلوب",
    "review.needAccountSub": "أنشئ حساب زبون مجاني لكتابة تقييم.",
    "profile.title": "الملف الشخصي",
    "profile.phone": "الهاتف",
    "profile.city": "المدينة",
    "profile.signOut": "تسجيل الخروج",
    "profile.guestTitle": "سجّل الدخول للمزيد",
    "profile.guestSub": "أنشئ حساب زبون مجاني لتتبع حجوزاتك وترك التقييمات.",
    "profile.guestCreate": "إنشاء حساب زبون",
    "profile.guestSignIn": "تسجيل الدخول",
    "profile.language": "اللغة",
    "dash.subDesc": "هذه نظرة على نشاطك اليوم.",
    "dash.subActive": "الاشتراك نشط",
    "dash.subTrial": "الفترة التجريبية نشطة",
    "dash.subDue": "الدفع مطلوب",
    "dash.subDeact": "الملف الشخصي معطل",
    "dash.subActiveSub": "يتجدد خلال {days} يومًا.",
    "dash.subTrialSub": "متبقٍ {days} يومًا. ثم 1000 دج/شهر.",
    "dash.subDueSub": "ادفع 1000 دج لإبقاء ملفك مدرجًا.",
    "dash.subDeactSub": "تواصل مع الدعم لإعادة التفعيل.",
    "dash.pay": "ادفع 1000 دج",
    "dash.renew": "تجديد الآن",
    "dash.earned": "دج مكتسبة",
    "dash.completed": "منجزة",
    "dash.upcoming": "قادمة",
    "dash.pending": "قيد الانتظار",
    "dash.yourRating": "تقييمك",
    "dash.reviews": "تقييم",
    "dash.recent": "الحجوزات الأخيرة",
    "dash.noBookings": "لا توجد حجوزات",
    "dash.noBookingsSub": "سيرى العملاء ملفك في السوق.",
    "chat.title": "الرسائل",
    "chat.empty": "لا توجد محادثات",
    "chat.emptySub": "ابدأ محادثة من ملف مقدم الخدمة.",
    "chat.placeholder": "اكتب رسالة…",
    "chat.send": "إرسال",
    "chat.safety": "تحدث بأمان — دون الحاجة لمشاركة رقم هاتفك.",
    "chat.messageBtn": "مراسلة",
    "schedule.title": "جدولي",
    "schedule.workingHours": "ساعات العمل",
    "schedule.breaks": "الاستراحات",
    "schedule.vacation": "أيام الإجازة",
    "schedule.save": "حفظ",
    "schedule.saved": "تم حفظ الجدول",
    "schedule.offlineHint": "غير متصل · بيانات مخبأة",
    "schedule.closed": "مغلق",
    "schedule.setHours": "تحديد",
    "schedule.start": "البداية",
    "schedule.end": "النهاية",
    "schedule.tapDay": "اضغط على يوم لإضافة/إزالة إجازة",
    "schedule.langRestart": "تم تطبيق اللغة. أعد تشغيل التطبيق لتفعيل RTL بالكامل.",
    "address.suggestions": "اقتراحات",
    "address.searching": "بحث…",
    "day.mon": "الاثنين",
    "day.tue": "الثلاثاء",
    "day.wed": "الأربعاء",
    "day.thu": "الخميس",
    "day.fri": "الجمعة",
    "day.sat": "السبت",
    "day.sun": "الأحد",
    "otp.title": "المتابعة برقم الهاتف",
    "otp.subtitle": "سنرسل لك رمز التحقق المكون من 6 أرقام.",
    "otp.phone": "رقم الهاتف",
    "otp.sendCode": "إرسال الرمز",
    "otp.enterCode": "أدخل الرمز المرسل إلى",
    "otp.code": "رمز التحقق",
    "otp.verify": "تحقق",
    "otp.resend": "إعادة الإرسال",
    "otp.resendIn": "إعادة الإرسال خلال {sec} ثانية",
    "otp.wrongNumber": "رقم خاطئ؟",
    "otp.mockHint": "وضع تجريبي — تحقق من سجلات الخادم للحصول على الرمز.",
    "otp.iAm": "أنا",
    "otp.roleClient": "زبون",
    "otp.roleProvider": "مقدم خدمة",
    "otp.errPhone": "رقم جزائري غير صالح",
    "otp.errCode": "أدخل الرمز المكون من 6 أرقام",
    "profileC.title": "أكمل ملفك الشخصي",
    "profileC.sub": "بعض التفاصيل الأخيرة قبل البدء.",
    "profileC.save": "حفظ ومتابعة",
    "auth.orPhone": "أو المتابعة برقم الهاتف",
    "wilaya.select": "اختر الولاية",
    "wilaya.searchPh": "ابحث ضمن 58 ولاية…",
    "wilaya.mine": "ولايتي",
    "wilaya.crossOn": "متوفر في جميع الولايات",
    "wilaya.crossOff": "ولايتي فقط",
    "wilaya.baladiya": "البلدية",
    "wilaya.baladiyaPh": "مثل: باب الزوار",
    "wilaya.filterAll": "كل الجزائر",
    "booking.instant": "حجز فوري",
    "booking.instantSub": "بالتسعيرة المعلنة",
    "booking.quote": "طلب عرض سعر",
    "booking.quoteSub": "عمل معقد — سعر مخصص",
    "booking.pinTitle": "ضع دبوسًا على موقع الخدمة",
    "booking.pinHint": "اضغط على الخريطة أو اسحب الدبوس لتحديد الموقع بدقة.",
    "booking.pinConfirm": "تأكيد الموقع",
    "booking.locationSet": "تم تحديد الموقع",
    "report.title": "الإبلاغ عن مقدم الخدمة",
    "report.reason": "السبب",
    "report.details": "التفاصيل (اختياري)",
    "report.detailsPh": "أخبرنا بما حدث…",
    "report.submit": "إرسال البلاغ",
    "report.submitted": "تم إرسال البلاغ. شكرًا.",
    "report.reasons.noShow": "لم يحضر / لم يقدم الخدمة",
    "report.reasons.poorQuality": "جودة رديئة",
    "report.reasons.priceGouging": "مبالغة في السعر",
    "report.reasons.unsafe": "سلوك غير آمن",
    "report.reasons.fraud": "احتيال",
    "report.reasons.other": "أخرى",
    "report.needAccount": "يجب تسجيل الدخول للإبلاغ",
    "portfolio.title": "أعمالي",
    "portfolio.empty": "لا توجد صور بعد",
    "portfolio.add": "إضافة صورة",
    "portfolio.compressing": "جاري الضغط…",
    "portfolio.limit": "حتى 20 صورة",
    "portfolio.compressing": "جارٍ الضغط…",
    "portfolio.compressedInfo": "تم الضغط {before} → {after} ({passes} تمريرة)",
    "portfolio.cover": "الغلاف",
    "portfolio.setCover": "تعيين كغلاف",
    "portfolio.isCover": "هذه هي صورة الغلاف الخاصة بك",
    "portfolio.editorTitle": "تعديل الصورة",
    "portfolio.caption": "تعليق",
    "portfolio.captionPh": "مثال: طلاء المطبخ · باب الزوار، جوان 2026",
    "portfolio.tags": "التصنيفات",
    "portfolio.save": "حفظ",
    "portfolio.tag_before": "قبل",
    "portfolio.tag_after": "بعد",
    "portfolio.tag_residential": "سكني",
    "portfolio.tag_commercial": "تجاري",
    "portfolio.tag_interior": "داخلي",
    "portfolio.tag_exterior": "خارجي",
    "portfolio.tag_detail": "تفصيل",
    "portfolio.tag_custom": "خاص",
    // Verification
    "verify.title": "الثقة والتوثيق",
    "verify.status.unverified": "غير موثّق",
    "verify.status.pending": "قيد المراجعة",
    "verify.status.verified": "موثّق",
    "verify.status.rejected": "مرفوض",
    "verify.desc.unverified": "احصل على شارة التوثيق على ملفك بإرسال بطاقة هويتك (والشهادات اختياريًا). المزوّدون الموثّقون يحصلون على حجوزات أكثر.",
    "verify.desc.pending": "فريقنا يراجع مستنداتك. المدة عادةً من 1 إلى 3 أيام عمل.",
    "verify.desc.verified": "أنت موثّق! يظهر شارة الثقة بجانب اسمك.",
    "verify.desc.rejected": "تم رفض طلبك. راجع السبب أدناه وأعد الإرسال.",
    "verify.submitted": "تم إرسال {n} مستندًا — بانتظار المراجعة",
    "verify.startCta": "ابدأ التوثيق",
    "verify.resubmit": "أعد الإرسال",
    "verify.submitCta": "إرسال للمراجعة",
    "verify.uploaderSub": "ارفع صورًا واضحة للمستندات المطلوبة. الصور تُضغط محليًا على جهازك قبل الرفع.",
    "verify.required": "مطلوب",
    "verify.compressing": "جارٍ الضغط…",
    "verify.upload": "رفع",
    "verify.idRecto": "بطاقة التعريف — الوجه",
    "verify.idRectoHint": "يجب أن يكون الاسم والصورة والرقم واضحين.",
    "verify.idVerso": "بطاقة التعريف — الظهر",
    "verify.idVersoHint": "الوجهان يساعدان على تأكيد هويتك.",
    "verify.certification": "شهادة مهنية",
    "verify.certificationHint": "شهادة حرفية أو دبلوم أو رخصة (اختياري).",
    "verify.background": "السجل العدلي",
    "verify.backgroundHint": "مستخرج من السجل العدلي أو ما يعادله (اختياري).",
    "verify.badgeShort": "موثّق",
    // Admin
    "admin.title": "قائمة انتظار التوثيق",
    "admin.empty": "لا توجد طلبات توثيق معلّقة 🎉",
    "admin.forbidden": "مطلوب صلاحيات المشرف",
    "admin.goHome": "العودة للتطبيق",
    "admin.submitted": "أُرسل بتاريخ",
    "admin.approve": "قبول",
    "admin.reject": "رفض",
    "admin.rejectTitle": "رفض التوثيق",
    "admin.rejectSub": "سيرى المزوّد السبب وسيتمكن من إعادة إرسال المستندات.",
    "admin.rejectPh": "مثال: صورة البطاقة غير واضحة — يرجى إعادة الرفع مع إضاءة أفضل.",
    "admin.unnamed": "مزوّد بدون اسم",
    "common.retry": "إعادة المحاولة",
    // Admin flags
    "flags.title": "المزوّدون المُبلَّغ عنهم",
    "flags.empty": "لا يوجد مزوّدون مُبلَّغ عنهم 🎉",
    "flags.bannerSub": "{n} مزوّد(ون) تم الإبلاغ عنهم تلقائيًا",
    "flags.reason": "السبب",
    "flags.flaggedAt": "تاريخ الإبلاغ",
    "flags.completion": "نسبة الإنجاز",
    "flags.clear": "إزالة الإبلاغ وإعادة التفعيل",
    "flags.confirmTitle": "إزالة هذا الإبلاغ؟",
    "flags.confirmSub": "سيتم إعادة تفعيل المزوّد وإزالة عقوبة البحث.",
    "flags.section": "بلاغات تلقائية",
    "flags.sectionSub": "المزوّدون الذين تم الإبلاغ عنهم تلقائيًا",
    // Account settings
    "account.section": "الحساب",
    "account.subscription": "الاشتراك",
    "account.subActive": "اشتراك نشط",
    "account.subTrial": "فترة تجريبية",
    "account.subDue": "الدفع مطلوب",
    "account.subDeact": "معطّل",
    "account.subDeleted": "محذوف",
    "account.subManual": "معطّل يدويًا",
    "account.daysLeftTrial": "متبقٍ {days} يومًا في الفترة التجريبية",
    "account.daysLeftActive": "يتجدد خلال {days} يومًا",
    "account.dueNow": "ادفع 1000 دج الآن لإبقاء ملفك مدرجًا.",
    "account.willAutoDelete": "سيتم حذف الملف تلقائيًا بعد 12 شهرًا من عدم الدفع.",
    "account.payNow": "ادفع 1000 دج",
    "account.paying": "جارٍ المعالجة…",
    "account.paySuccess": "تم استلام الدفع — شكرًا!",
    "account.dangerZone": "منطقة الخطر",
    "account.deactivate": "تعطيل الحساب",
    "account.deactivateSub": "إخفاء ملفك مؤقتًا. يمكنك إعادة التفعيل في أي وقت.",
    "account.reactivate": "إعادة تفعيل الحساب",
    "account.reactivateSub": "استعد حسابك واجعل ملفك مرئيًا مرة أخرى.",
    "account.delete": "حذف الحساب",
    "account.deleteSub": "إزالة نهائية للحساب. لا يمكن التراجع.",
    "account.switchRole": "تغيير الدور / العودة للبداية",
    "account.switchRoleSub": "تسجيل الخروج والعودة للشاشة الأولى لاختيار دور مختلف.",
    "account.confirmDeactivate": "تعطيل الحساب؟",
    "account.confirmDeactivateSub": "سيتم إخفاء ملفك حتى تعيد التفعيل.",
    "account.confirmDelete": "حذف الحساب؟",
    "account.confirmDeleteSub": "هذا نهائي. سيتم إخفاء الحجوزات والتقييمات والرسائل ولن تستطيع تسجيل الدخول.",
    "account.confirmReactivate": "إعادة تفعيل الحساب؟",
    "account.confirmReactivateSub": "سيصبح ملفك مرئيًا للعملاء مرة أخرى.",
    "account.cancel": "إلغاء",
    "account.confirm": "تأكيد",
    "account.deleted": "تم حذف الحساب",
    "account.deletedSub": "تم حذف حسابك نهائيًا.",
    "account.deactivated": "تم تعطيل الحساب",
    "account.reactivated": "تم إعادة التفعيل",
    "account.deactBanner": "حسابك معطّل حاليًا. أعد التفعيل لتظهر في البحث.",
    "account.mockPay": "بوابة الدفع تجريبية في هذا الإصدار.",
  },
};

type LangCtx = {
  lang: Lang;
  isRTL: boolean;
  setLang: (l: Lang) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
};

const Ctx = createContext<LangCtx | undefined>(undefined);

async function readLang(): Promise<Lang | null> {
  if (Platform.OS === "web") return null;
  try {
    const v = await SecureStore.getItemAsync(STORAGE_KEY);
    if (v === "en" || v === "fr" || v === "ar") return v;
  } catch {}
  return null;
}

async function writeLang(l: Lang) {
  if (Platform.OS === "web") return;
  try {
    await SecureStore.setItemAsync(STORAGE_KEY, l);
  } catch {}
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>("en");

  useEffect(() => {
    (async () => {
      const saved = await readLang();
      if (saved) setLangState(saved);
      // Apply RTL layout ONLY when Arabic is selected. On native this requires
      // an app reload to take full effect for flex direction; text-level RTL
      // (writingDirection) is applied per-component below.
      const shouldRTL = (saved || "en") === "ar";
      try {
        // Always write the desired state so an old "forceRTL(true)" from a
        // previous session is explicitly cleared when the user is no longer
        // on Arabic.
        I18nManager.allowRTL(shouldRTL);
        I18nManager.forceRTL(shouldRTL);
      } catch {}
    })();
  }, []);

  const setLang = useCallback((l: Lang) => {
    setLangState(l);
    writeLang(l);
    // Toggle RTL. Restart needed on native for full effect (user is prompted in UI).
    try {
      const rtl = l === "ar";
      // Always write both flags so switching Arabic → English/French truly
      // clears RTL, not just when the flag currently differs.
      I18nManager.allowRTL(rtl);
      I18nManager.forceRTL(rtl);
    } catch {}
  }, []);

  const t = useCallback(
    (key: string, params?: Record<string, string | number>) => {
      let s = dict[lang][key] || dict.en[key] || key;
      if (params) {
        Object.entries(params).forEach(([k, v]) => {
          s = s.replace(`{${k}}`, String(v));
        });
      }
      return s;
    },
    [lang]
  );

  const value: LangCtx = {
    lang,
    isRTL: lang === "ar",
    setLang,
    t,
  };

  return <Ctx.Provider value={value}>{children}</Ctx.Provider>;
}

export function useT() {
  const c = useContext(Ctx);
  if (!c) throw new Error("useT must be used inside LanguageProvider");
  return c;
}
